version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: opentofu
    directory: /deploy/gke/stacks/cluster
    schedule:
      interval: weekly
  - package-ecosystem: opentofu
    directory: /deploy/gke/stacks/app-edge
    schedule:
      interval: weekly
  - package-ecosystem: opentofu
    directory: /deploy/gke/stacks/day2-app
    schedule:
      interval: weekly
  - package-ecosystem: opentofu
    directory: /deploy/gke/stacks/qualification-runner
    schedule:
      interval: weekly
