use anyhow::{Context, Result};
use day2_control::{
    BindingRef, BuildPlan, Digest, GitOid, Name,
    build::{
        BuildRequest, PinnedTree, PlatformInputs, TrustedRunner, recipe_digest, supported_host,
    },
    contracts::BuildProfile,
    source::SourceSnapshot,
};
use serde_json::json;
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

fn name(value: &str) -> Name {
    Name::try_from(value.to_owned()).unwrap()
}
fn commit(value: char) -> GitOid {
    GitOid::try_from(value.to_string().repeat(40)).unwrap()
}

struct EvidenceDirectory(Option<tempfile::TempDir>);
impl EvidenceDirectory {
    fn new() -> Result<Self> {
        Ok(Self(Some(tempfile::tempdir()?)))
    }
    fn path(&self) -> &Path {
        self.0.as_ref().expect("live evidence directory").path()
    }
    fn close(mut self) -> Result<()> {
        let directory = self.0.take().context("live evidence directory")?;
        unseal(directory.path())?;
        directory.close()?;
        Ok(())
    }
}
impl Drop for EvidenceDirectory {
    fn drop(&mut self) {
        if let Some(directory) = self.0.take()
            && let Err(error) =
                unseal(directory.path()).and_then(|_| directory.close().map_err(Into::into))
        {
            eprintln!("evidence fixture cleanup failed: {error}");
        }
    }
}
fn unseal(path: &Path) -> Result<()> {
    let kind = fs::symlink_metadata(path)?.file_type();
    if kind.is_symlink() {
        return Ok(());
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(
            path,
            fs::Permissions::from_mode(if kind.is_dir() { 0o700 } else { 0o600 }),
        )?;
    }
    if kind.is_dir() {
        for entry in fs::read_dir(path)? {
            unseal(&entry?.path())?;
        }
    }
    Ok(())
}

fn write(path: &Path, value: &[u8], executable: bool) -> Result<()> {
    fs::create_dir_all(path.parent().context("file parent")?)?;
    fs::write(path, value)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(
            path,
            fs::Permissions::from_mode(if executable { 0o755 } else { 0o644 }),
        )?;
    }
    Ok(())
}

fn platform(directory: &Path) -> Result<PlatformInputs> {
    let root = directory.join("platform");
    for name in [
        "Cargo.toml",
        "Cargo.lock",
        "architecture-rules.json",
        "architecture-boundaries.json",
        "rust-toolchain.toml",
        "toolchain.json",
        ".dockerignore",
        "LICENSE",
        "THIRD-PARTY-NOTICES.txt",
        "dependency-inventory.json",
    ] {
        write(&root.join(name), b"approved platform input", false)?;
    }
    for name in [
        "crates",
        "sdk",
        "tools",
        "vendor",
        "assets",
        "fixtures",
        "examples",
        "ops",
        "infra",
        "cli",
        "toolchains",
        "deploy",
    ] {
        fs::create_dir_all(root.join(name))?;
    }
    write(&root.join("cli/main.roc"), b"approved CLI", false)?;
    write(
        &root.join("ops/Workflow.roc"),
        b"approved operations",
        false,
    )?;
    write(
        &root.join("infra/Stack.roc"),
        b"approved infrastructure",
        false,
    )?;
    for name in [
        "day2",
        "day2-host",
        "day2-sandbox",
        "day2-sandbox-probe",
        "day2-compiler-sandbox",
        "xtask",
        "distribution.json",
        ".cache/ignored",
    ] {
        write(&root.join("cli").join(name), b"mutable distribution", false)?;
    }
    write(
        &root.join("crates/worker/generated/host.rs"),
        b"stale generated bytes",
        false,
    )?;
    write(
        &root.join("crates/worker/src/lib.rs"),
        b"approved Rust",
        false,
    )?;
    write(
        &root.join("fixtures/authority-policies/owned.json"),
        b"approved policy",
        false,
    )?;
    write(&root.join("artifacts/secret"), b"not an input", false)?;
    write(&root.join("target/shared"), b"not an input", false)?;
    write(&directory.join(".toolchains/roc"), b"pinned Roc", true)?;
    write(
        &directory.join(".toolchains/darwin/usr/lib/libSystem.tbd"),
        b"pinned linker",
        false,
    )?;
    PlatformInputs::capture(&root, &directory.join(".toolchains"))
}

#[test]
fn architecture_policy_changes_invalidate_the_platform_and_materialization() -> Result<()> {
    for policy in ["architecture-rules.json", "architecture-boundaries.json"] {
        let directory = tempfile::tempdir()?;
        let approved = platform(directory.path())?;
        write(
            &directory.path().join("platform").join(policy),
            b"changed architecture policy",
            false,
        )?;
        let changed = PlatformInputs::capture(
            &directory.path().join("platform"),
            &directory.path().join(".toolchains"),
        )?;
        assert_ne!(approved.digest(), changed.digest());
        let staged = directory.path().join("staged");
        fs::create_dir(&staged)?;
        assert!(approved.materialize(&staged).is_err());
    }
    Ok(())
}

fn runner(directory: &Path) -> Result<TrustedRunner> {
    write(&directory.join("xtask"), b"pinned central executor", true)?;
    for executable in ["cargo", "rustc"] {
        write(
            &directory.join("rust/bin").join(executable),
            b"pinned Rust executable",
            true,
        )?;
    }
    write(
        &directory.join("registry/src/approved-crate/lib.rs"),
        b"approved dependency",
        false,
    )?;
    TrustedRunner::capture(
        name("local-runner"),
        &directory.join("xtask"),
        &directory.join("rust"),
        &directory.join("registry"),
    )
}

fn request(runner: &TrustedRunner, platform: &PlatformInputs) -> Result<BuildRequest> {
    Ok(BuildRequest {
        plan: BuildPlan {
            version: 1,
            company: name("exampleco"),
            app: name("owned_links"),
            request: name("first-build"),
            commit: commit('a'),
            profile: BuildProfile {
                source: BindingRef::pin(name("github-source"), &json!({"repository_id":123}))?,
                builder: runner.binding()?,
                durability: BindingRef::pin(name("temporal"), &json!({"namespace":"day2-local"}))?,
                platform: platform.digest().clone(),
                recipe: recipe_digest(),
            },
        },
        source: SourceSnapshot::from_files(
            commit('a'),
            BTreeMap::from([("App.roc".into(), b"App :: [].{}\n".to_vec())]),
        )?,
    })
}

#[test]
fn pinned_tree_copies_only_admitted_bytes_and_rejects_substitution() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let source = directory.path().join("source");
    write(&source.join("code/file.roc"), b"original source", false)?;
    let approved = PinnedTree::capture(&source)?;
    write(&source.join("later-secret"), b"unapproved", false)?;
    let target = directory.path().join("target");
    approved.materialize(&target)?;
    assert_eq!(fs::read(target.join("code/file.roc"))?, b"original source");
    assert!(!target.join("later-secret").exists());
    assert!(approved.materialize(&target).is_err());
    write(&source.join("code/file.roc"), b"substituted source", false)?;
    assert!(
        approved
            .materialize(&directory.path().join("changed"))
            .is_err()
    );
    assert_ne!(approved.digest(), PinnedTree::capture(&source)?.digest());
    Ok(())
}

#[cfg(unix)]
#[test]
fn pinned_inputs_refuse_symlinks_and_preserve_approved_execution_modes() -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let directory = tempfile::tempdir()?;
    let source = directory.path().join("source");
    write(&source.join("executable"), b"executable", true)?;
    write(&source.join("data"), b"data", false)?;
    let tree = PinnedTree::capture(&source)?;
    let target = directory.path().join("target");
    tree.materialize(&target)?;
    assert_eq!(
        fs::metadata(target.join("executable"))?
            .permissions()
            .mode()
            & 0o777,
        0o555
    );
    assert_eq!(
        fs::metadata(target.join("data"))?.permissions().mode() & 0o777,
        0o444
    );
    std::os::unix::fs::symlink(source.join("data"), source.join("link"))?;
    assert!(PinnedTree::capture(&source).is_err());
    fs::remove_file(source.join("link"))?;
    fs::remove_file(source.join("data"))?;
    std::os::unix::fs::symlink(source.join("executable"), source.join("data"))?;
    assert!(
        tree.materialize(&directory.path().join("swapped-link"))
            .is_err()
    );
    Ok(())
}

#[test]
fn platform_snapshot_excludes_mutable_shared_outputs_but_pins_policy_and_toolchain() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let approved = platform(directory.path())?;
    assert!(
        !approved
            .files()
            .keys()
            .any(|name| name.contains("generated")
                || name.contains("artifacts/")
                || name.contains("target/"))
    );
    assert!(
        approved
            .files()
            .contains_key("platform/fixtures/authority-policies/owned.json")
    );
    assert!(approved.files().contains_key(".toolchains/roc"));
    for name in ["cli/main.roc", "ops/Workflow.roc", "infra/Stack.roc"] {
        assert!(approved.files().contains_key(&format!("platform/{name}")));
    }
    assert_eq!(
        approved
            .files()
            .keys()
            .filter(|name| name.starts_with("platform/cli/"))
            .count(),
        1
    );
    for name in [
        "deploy/gke/.terraform/provider",
        "deploy/gke/terraform.tfstate",
        "deploy/gke/private.tfvars",
        "examples/instance/.env",
        "examples/instance/credentials.json",
    ] {
        write(
            &directory.path().join("platform").join(name),
            b"private local input",
            false,
        )?;
    }
    let recaptured = PlatformInputs::capture(
        &directory.path().join("platform"),
        &directory.path().join(".toolchains"),
    )?;
    assert_eq!(approved.digest(), recaptured.digest());
    let private = directory.path().join("private");
    fs::create_dir(&private)?;
    approved.materialize(&private)?;
    assert!(!private.join("platform/artifacts").exists());
    assert!(!private.join("platform/crates/worker/generated").exists());
    assert_eq!(
        fs::read(private.join("platform/fixtures/authority-policies/owned.json"))?,
        b"approved policy"
    );
    write(
        &directory
            .path()
            .join("platform/fixtures/authority-policies/owned.json"),
        b"changed policy",
        false,
    )?;
    let second = directory.path().join("second");
    fs::create_dir(&second)?;
    assert!(approved.materialize(&second).is_err());
    Ok(())
}

#[test]
fn build_request_cannot_mix_a_commit_platform_runner_or_recipe() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let platform = platform(directory.path())?;
    let runner = runner(directory.path())?;
    let mut request = request(&runner, &platform)?;
    runner.validate_request(&request, &platform)?;
    request.plan.commit = commit('b');
    assert!(runner.validate_request(&request, &platform).is_err());
    request.plan.commit = commit('a');
    request.plan.profile.platform = Digest::new(b"different platform");
    assert!(runner.validate_request(&request, &platform).is_err());
    request.plan.profile.platform = platform.digest().clone();
    request.plan.profile.recipe = Digest::new(b"arbitrary app script");
    assert!(runner.validate_request(&request, &platform).is_err());
    request.plan.profile.recipe = recipe_digest();
    request.plan.profile.builder.revision = Digest::new(b"different runner");
    assert!(runner.validate_request(&request, &platform).is_err());
    Ok(())
}

#[test]
fn runner_binding_pins_its_dependency_cache_and_refuses_cargo_credentials() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let first = runner(directory.path())?;
    write(
        &directory.path().join("registry/src/approved-crate/lib.rs"),
        b"different dependency",
        false,
    )?;
    let second = TrustedRunner::capture(
        name("local-runner"),
        &directory.path().join("xtask"),
        &directory.path().join("rust"),
        &directory.path().join("registry"),
    )?;
    assert_ne!(first.binding()?, second.binding()?);
    write(
        &directory.path().join("registry/credentials.toml"),
        b"must not reach a build",
        false,
    )?;
    assert!(
        TrustedRunner::capture(
            name("local-runner"),
            &directory.path().join("xtask"),
            &directory.path().join("rust"),
            &directory.path().join("registry")
        )
        .is_err()
    );
    fs::remove_file(directory.path().join("registry/credentials.toml"))?;
    write(
        &directory.path().join("registry/index/legacy/.git/config"),
        b"credential-bearing Git configuration must not be read",
        false,
    )?;
    let error = TrustedRunner::capture(
        name("local-runner"),
        &directory.path().join("xtask"),
        &directory.path().join("rust"),
        &directory.path().join("registry"),
    )
    .unwrap_err();
    assert!(error.to_string().contains("VCS metadata"));
    Ok(())
}

#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
#[test]
fn a_fast_successful_process_cannot_bypass_the_log_budget_or_forge_verification() -> Result<()> {
    let directory = EvidenceDirectory::new()?;
    let platform = platform(directory.path())?;
    let _ = runner(directory.path())?;
    let program = directory.path().join("flood.rs");
    fs::write(
        &program,
        r#"use std::io::Write;
        fn main() { std::io::stdout().write_all(&vec![b'x'; 17*1024*1024]).unwrap(); }"#,
    )?;
    assert!(
        std::process::Command::new("rustc")
            .arg(&program)
            .arg("-o")
            .arg(directory.path().join("flood"))
            .status()?
            .success()
    );
    let runner = TrustedRunner::capture(
        name("flood-fixture"),
        &directory.path().join("flood"),
        &directory.path().join("rust"),
        &directory.path().join("registry"),
    )?;
    let request = request(&runner, &platform)?;
    let outputs = directory.path().join("outputs");
    let evidence = runner.execute(&request, &platform, &outputs)?;
    assert!(evidence.verification_evidence().is_err());
    assert!(evidence.failure().is_some());
    let stored = TrustedRunner::evidence_directory(&request, &outputs)?;
    assert!(fs::metadata(stored.join("build.log"))?.len() <= 16 * 1024 * 1024);
    assert_eq!(
        runner.execute(&request, &platform, &outputs)?.digest()?,
        evidence.digest()?
    );
    directory.close()
}

#[test]
fn unsupported_build_hosts_fail_closed() {
    assert_eq!(
        supported_host().is_ok(),
        cfg!(all(target_os = "macos", target_arch = "aarch64"))
    );
}

#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
#[test]
fn cargo_stage_sandbox_allows_private_reads_but_denies_host_data_and_writes() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let job = directory.path().join("job");
    fs::create_dir(&job)?;
    let cat = job.join("cat");
    let canary = job.join("canary.rs");
    fs::write(
        &canary,
        r#"fn main() {
        let args: Vec<String> = std::env::args().collect();
        let result = if args[1] == "write" { std::fs::write(&args[2], b"forbidden replacement") }
        else { std::fs::read_to_string(&args[1]).map(|text| print!("{text}")) };
        if result.is_err() { std::process::exit(1); }
    }"#,
    )?;
    assert!(
        std::process::Command::new("rustc")
            .arg(&canary)
            .arg("-o")
            .arg(&cat)
            .status()?
            .success()
    );
    write(&job.join("allowed"), b"private build input", false)?;
    let outside = directory.path().join("secret");
    write(&outside, b"outside host data", false)?;
    let allowed = day2::sandbox::build_host(&job, &cat)?
        .arg(job.join("allowed"))
        .env_clear()
        .output()?;
    assert!(
        allowed.status.success(),
        "{}",
        String::from_utf8_lossy(&allowed.stderr)
    );
    assert_eq!(allowed.stdout, b"private build input");
    let denied = day2::sandbox::build_host(&job, &cat)?
        .arg(&outside)
        .env_clear()
        .output()?;
    assert!(!denied.status.success());
    assert!(denied.stdout.is_empty());
    let denied = day2::sandbox::build_host(&job, &cat)?
        .arg("write")
        .arg(&outside)
        .env_clear()
        .output()?;
    assert!(!denied.status.success());
    assert_eq!(fs::read(&outside)?, b"outside host data");
    Ok(())
}

#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
#[test]
#[ignore = "requires DAY2_TEST_BUILD_RUST for pinned native Cargo launch diagnostic"]
fn cargo_stage_sandbox_starts_the_real_cargo_binary() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let cargo = directory.path().join("cargo");
    let rust = std::env::var_os("DAY2_TEST_BUILD_RUST")
        .map(PathBuf::from)
        .context("DAY2_TEST_BUILD_RUST")?;
    fs::copy(rust.join("bin/cargo"), &cargo)?;
    let output = day2::sandbox::build_host(directory.path(), &cargo)?
        .arg("--version")
        .current_dir(directory.path())
        .env_clear()
        .env("OPENSSL_CONF", "/dev/null")
        .env("HOME", directory.path())
        .output()?;
    assert!(
        output.status.success(),
        "{:?}: {}",
        output.status,
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(String::from_utf8_lossy(&output.stdout).starts_with("cargo "));
    Ok(())
}

#[test]
#[ignore = "explicit operator-pinned macOS runner smoke; requires DAY2_TEST_BUILD_* paths"]
fn real_isolated_owned_links_build_produces_bound_evidence_and_recovers_receipt() -> Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()?;
    let path = |name: &str| {
        std::env::var_os(name)
            .map(PathBuf::from)
            .with_context(|| format!("missing {name}"))
    };
    let runner = TrustedRunner::capture(
        name("local-macos-runner"),
        &path("DAY2_TEST_BUILD_XTASK")?,
        &path("DAY2_TEST_BUILD_RUST")?,
        &path("DAY2_TEST_BUILD_REGISTRY")?,
    )?;
    let platform = PlatformInputs::capture(&root, &root.join("../.toolchains"))?;
    let source_tree = PinnedTree::capture(&root.join("fixtures/row-authority-web-conformance"))?;
    let source = SourceSnapshot::from_files(
        commit('a'),
        source_tree
            .files()
            .keys()
            .map(|name| {
                Ok((
                    name.clone(),
                    fs::read(
                        root.join("fixtures/row-authority-web-conformance")
                            .join(name),
                    )?,
                ))
            })
            .collect::<Result<_>>()?,
    )?;
    let mut request = request(&runner, &platform)?;
    request.source = source;
    let directory = EvidenceDirectory::new()?;
    let evidence = runner.execute(&request, &platform, directory.path())?;
    if evidence.failure().is_some() {
        let log = fs::read(
            TrustedRunner::evidence_directory(&request, directory.path())?.join("build.log"),
        )?;
        eprintln!(
            "{}",
            String::from_utf8_lossy(&log[log.len().saturating_sub(8192)..])
        );
    }
    let verified = evidence.verification_evidence().with_context(|| {
        format!(
            "local build failed: {:?}; evidence {}",
            evidence.failure(),
            directory.path().display()
        )
    })?;
    assert_eq!(verified.source, *request.source.digest());
    assert_eq!(verified.plan, request.plan.fingerprint()?);
    assert_eq!(
        verified.credential_presence,
        day2_control::kernel::CredentialPresence::Absent
    );
    let receipt = runner.execute(&request, &platform, directory.path())?;
    assert_eq!(receipt.digest()?, evidence.digest()?);
    assert_eq!(
        receipt.verification_evidence()?.credential_presence,
        verified.credential_presence
    );
    let result = TrustedRunner::evidence_directory(&request, directory.path())?;
    assert_eq!(
        day2::artifact::LoadedArtifact::load(&evidence.artifact_directory(&result)?)?.id(),
        verified.artifact.as_str()
    );
    directory.close()
}
